export const merchItems = [
  {
    id: "1",
    name: "The Art of Shantae SDCC Edition",
    thumbnail: "images/the_art_of_shantae_1.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "2",
    name: "The Art of Shantae",
    thumbnail: "images/the_art_of_shantae_2.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "3",
    name: "Tropical Trickster T-Shirt",
    thumbnail: "images/tropical_shirt.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "4",
    name: "Tropical Blacklight T-Shirt",
    thumbnail: "images/tropical_blacklight.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "5",
    name: "Charagumin Shantae Figurine",
    thumbnail: "images/charagumin_shantae.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "6",
    name: "Charagumin Risky Boots Figurine",
    thumbnail: "images/charagumin_riskyboots.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "7",
    name: "Charagumin Rottytops Figurine",
    thumbnail: "images/charagumin_rottytops.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "8",
    name: "Charagumin Sky Figurine",
    thumbnail: "images/charagumin_sky.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "9",
    name: "Shantae Nendoroid Figurine",
    thumbnail: "images/nendoroid_shantae.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "10",
    name: "LRG Classic Shantae Pogs",
    thumbnail: "images/classic_shantae_pog.png",
    game: "GBC",
    haveState: null,
  },
  {
    id: "11",
    name: "Shantae Risky's Revenge Vinyl",
    thumbnail: "images/risky_s-revenge_vinyl.png",
    game: "RR",
    haveState: null,
  },
  {
    id: "12",
    name: "Shantae 2022 Vinyl Red",
    thumbnail: "images/product_shantae_vinyl_2022_front.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "13",
    name: "Shantae Plush",
    thumbnail: "images/shantae_plush.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "14",
    name: "Rottytops Plush",
    thumbnail: "images/rottytops_plush.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "15",
    name: "Shantae GBC (Limited Run Games)",
    thumbnail: "images/shantae_gbc_lrg.png",
    game: "GBC",
    haveState: null,
  },
  {
    id: "16",
    name: "Shantae GBC (Capcom)",
    thumbnail: "images/shantae_gbc_real.png",
    game: "GBC",
    haveState: null,
  },
  {
    id: "17",
    name: "Shantae and the Pirate's Curse T-Shirt",
    thumbnail: "images/pirate's_curse_t-shirt.png",
    game: "PC",
    haveState: null,
  },
  {
    id: "18",
    name: "Half-Genie Hero Sticker Set",
    thumbnail: "images/HGH-Sticker-Set.png",
    game: "HGH",
    haveState: null,
  },
  {
    id: "19",
    name: "Half-Genie Hero Techno Grunt Keychain",
    thumbnail: "images/HGH-Techno-Grunt-Keychain.png",
    game: "HGH",
    haveState: null,
  },
  {
    id: "20",
    name: "Half-Genie Hero Trading Card Set",
    thumbnail: "images/HGH-Trading-Card-Set.png",
    game: "GBC",
    haveState: null,
  },
  {
    id: "21",
    name: "Shantae 20th Anniversary Statue",
    thumbnail: "images/shantae_20th_anni_statue.png",
    game: "Other",
    haveState: null,
  },
  {
    id: "22",
    name: "Shantae Blister Pack Acrylic",
    thumbnail: "images/shantae_blister_pack_acrylic.webp",
    game: "SS",
    haveState: null,
  },
  {
    id: "23",
    name: "Shantae and The Pirate's Curse Bikini Skateboard Deck",
    thumbnail: "images/shantae_pirate's_curse_skateboard.png",
    game: "PC",
    haveState: null,
  },
  {
    id: "24",
    name: "Shantae Retro Beach T-Shirt",
    thumbnail: "images/shantae_retro_beach_tee.webp",
    game: "other",
    haveState: null,
  },
  {
    id: "25",
    name: "Shantae GBC Soundtrack",
    thumbnail: "images/shantae_gbc_soundtrack_cd.png",
    game: "GBC",
    haveState: null,
  },
  {
    id: "26",
    name: "Shantae and the Pirate's Curse Risky Skull Cap",
    thumbnail: "images/shantae_pirate's_curse_hat.webp",
    game: "PC",
    haveState: null,
  },
  {
    id: "27",
    name: "Shantae and the Seven Sirens Skateboard Deck",
    thumbnail: "images/shantae_seven_sirens_skateboard.png",
    game: "SS",
    haveState: null,
  },
  {
    id: "28",
    name: "Shantae: Risky's Revenge Best Buy Exclusive Cover Sheet",
    thumbnail: "images/shantae_risky's_revenge_best_buy.png",
    game: "RR",
    haveState: null,
  },
];
